# path configuration
path:
  # template (or list of templates) --> null if you want to run an entire catalog
  filename: 
  # folder where templates are stored 
  catalog: input/afterglow
  # output where visibility table will be saved (used also as input for signigficance calculation)
  output: tables/LONG_FITS.noMoon.thresh24.NEW.npy
  # input XML model --> null if you want to run an entire catalog
<<<<<<< HEAD
  xml_filename: #model_Event*.xml
  # folder where input XML models are stored (the program looks for xml files even in subdirectories) 
  xml_dir:  path/to/xml_models/folder
  #output where significance table will be saved
  sigmaoutput: path/to/significance/output.npy

# site you want to analyse, leave blank if both
site: 

# seeds and iterations
random_seed: True   #Set True if you want the seed(s) to be chosen randomly
#number of times the simulation will be iterated. Can be set to 1 if you want 1 simulation with a random seed
iterations: 1
# If iterate is set to false you can choose a fixed seed value
seed: 


=======
  xml_filename: #model_Event100.xml
    # folder where input XML models are stored (the program looks for xml files even in subdirectories)
  xml_dir: models/subset2
    #output where significance table will be saved
  sigmaoutput: output/Events_101_200.North.iterations.noMoon.thresh24.hidden.npy

save_log: False
# leave empty if both sites must to be analysed
site: North

>>>>>>> 3f2e68899576ef76a1817453655d5cdb1cc02384
#Set True if you want the seed(s) to be chosen randomly
random_seed: True 
#number of times the simulation will be iterated. Can be set to 1 if you want 1 simulation with a random seed
iterations: 100
# If iterate is set to false you can choose a fixed seed value
seed: 
# stop simulation after 1h if sigma is still lower than 3
speed_up: True
#parameters to use for simulation with ctools
ctools:
<<<<<<< HEAD
   t_stop: #real number. Not null if you want to interrupt simualtion before end of simulation
=======
   t_stop: #87322.5
>>>>>>> 3f2e68899576ef76a1817453655d5cdb1cc02384
   #maximum value of energy up to wich simualte (TeV)
   emax : 10.0
   #calibration database       
   caldb: prod3b-v2
   #offset of on and off regions from the pointing center
   offset: 0.75
   #number of off regions
   off_regions: 5
   #repointing time delay   
   pointing_delay: 107.
   #stop iterating at N sigma?
   3sigma_stop: no
   5sigma_stop: no

verbosity: 0 # 0 solo l'essenziale, 1 qualcosina in più, 2 livello fastidio

