# path configuration
path:
  # template (or list of templates) --> null if you want to run an entire catalog
  filename: 
  # folder where templates are stored 
  catalog: /home/irene/cta/input/afterglow
  # output where visibility table will be saved (used also as input for signigficance calculation)
  output: /home/irene/provepy/VisCat/LONG_FITS.noMoon.thresh10.NEW.npy
  # input XML model --> null if you want to run an entire catalog
  xml_filename: model_Event54.xml
  # folder where input XML models are stored (the program looks for xml files even in subdirectories) 
  xml_dir: /home/irene/github/ctools/models/afterglow/Event54
  #output where significance table will be saved
  sigmaoutput: /home/irene/github/ctools/Evt54.North.noMoon.thresh10.npy
#parameters to use for simulation with ctools
ctools:
   #maximum value of energy up to wich simualte (TeV)
   emax : 10.0
   #simulation radius
   rad: 5.0
   #calibration database       
   caldb: prod3b-v2
   #number of times the simulation will be iterated
   iterations: 1
   #offset of on and off regions from the pointing center
   offset: 0.75
   #number of off regions
   off_regions: 5
   #repointing time delay   
   pointing_delay: 30. 
   #stop iterating at N sigma?
   3sigma_stop: no
   5sigma_stop: no

