# path configuration
path:
  # template (or list of templates) --> null if you want to run an entire catalog
  filename: 
  # folder where templates are stored 
  catalog: /path/to/fits_files/dir
  # output where visibility table will be saved (used also as input for signigficance calculation)
  output: /path/to/visibility_tables.npy
  # input XML model --> null if you want to run an entire catalog
  xml_filename: 
    # folder where input XML models are stored (the program looks for xml files even in subdirectories)
  xml_dir: path/t/xml_files/dir
    #output where significance table will be saved
  sigmaoutput: /path/to/output.npy

save_log: False
# leave empty if both sites must to be analysed
site: North

#Set True if you want the seed(s) to be chosen randomly
random_seed: True 
#number of times the simulation will be iterated. Can be set to 1 if you want 1 simulation with a random seed
iterations: 100
# If iterate is set to false you can choose a fixed seed value
seed: 
# stop simulation after 1h if sigma is still lower than 3
speed_up: True
#parameters to use for simulation with ctools
ctools:
   # stop time in seconds (delta_T). Null to integrate for total vis time
   t_stop: 
   #maximum value of energy up to wich simualte (TeV)
   emax : 10.0
   #calibration database       
   caldb: prod3b-v2
   #offset of on and off regions from the pointing center
   offset: 0.75
   #number of off regions
   off_regions: 5
   #repointing time delay   
   pointing_delay: 107.
   #stop iterating at N sigma?
   3sigma_stop: no
   5sigma_stop: no

verbosity: 0 # 0 solo l'essenziale, 1 qualcosina in più, 2 livello fastidio
