# path configuration
path:
  # template (or list of templates) --> null if you want to run an entire catalog
  filename: 
  # folder where templates are stored 
  catalog: /home/irene/cta/input/afterglow
  # output where visibility table will be saved (used also as input for signigficance calculation)
  output: /home/irene/cta/ctools-sci-grb/LONG_FITS.noMoon.thresh10.npy
  # input XML model --> null if you want to run an entire catalog
  xmlfilename: model_Event751.xml
  # folder where input XML models are stored (the program looks for xml files even in subdirectories) --> null if you want to run a single template 
  xmlcatalog: /home/irene/cta/models/afterglow/Event751
  #output where significance table will be saved
  sigmaoutput: /home/irene/provepy/Event751.noMoon.thresh10.npy
# observation setup
setup:
  # sub altitude below which starts the night (for astronomical darkness set -18)
  twilight: -18
  # min angular separationhttps://github.com/cta-rta/ctools-sci-grb from Moon 
  moon_sep: 30
  # max moon phase (range 0-1) threshold of observability
  moon_pha: 0.8
  # FoV radius (min angular separation will be added to this); set 0 if moon_sep wrt pointing
  fov_rad: 3
  # altitude (lower) thresholds for IRFs ranges
  thresholds:
    - 10
    - 36
    - 57
  # relative IRFs zenith angle
  zenith_angles:
    - 60
    - 40
    - 20
# all sites
sites_list:
  North: Roque de los Muchachos
  South: Paranal
# total grid points (only if use_visibility_table: no)
total_points: 100
# grid points within visibility window
window_points: 10
#parameters to use for simulation with ctools
ctools:
 #simulation radius
   rad: 5.0
 #xml model to be used for likelihood
   fitmodel: /home/irene/cta/template/GRB_expcut_v1.xml 
 #calibration database       
   caldb: prod3b-v2
 #maximum energy value
   Emax: 2. 
 #seed
   iterations: 100
  #t_stop
   duration :  1732.2
   offset: 0.6
   radius: 0.20
 



